version: '3.8'

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: ceregati_postgres
    restart: always
    environment:
      POSTGRES_USER: admin_ceregati
      POSTGRES_PASSWORD: SecretPassword123!
      POSTGRES_DB: ceregati_logistics_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata_ceregati:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ceregati_network

networks:
  ceregati_network:
    driver: bridge

volumes:
  pgdata_ceregati: